name: Goal Tracker CI

on:
  push:
    branches:
        - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository files
        run: ls -la

      - name: Display success message
        run: echo "Github Actions is working!"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4
